disabled_rules:
  - trailing_whitespace
  - line_length

opt_in_rules:
  - force_unwrapping
  - empty_count

included:
  - Sources
excluded:
  - Tests
  - Pods

line_length:
  warning: 120
  error: 150
